### ISSUE TITLE
No Commands Respond

### ISSUE THREAD

**Issue by imrohitkumar** [sumitsahoo/RASA-With-Aimybox#2]
Aimybox application which you have made, is not responding on any command.
it just pretends to be listening when clicked on mouse but it didn't responds anything.

**Comment by sumitsahoo** [comment]
Can I have logs please ?

**Comment by imrohitkumar** [comment]
I don't have good knowledge of collecting logs but here are collected from logcollector apk
Log Collector version: 1.2.0
Device model: POCO F1
Firmware version: 11
Kernel version: Unavailable
Build number: RQ1A.210105.003

--------- beginning of main
02-15 17:41:38.206 E/id.logcollecto( 9330): Not starting debugger since process cannot load the jdwp agent.
02-15 17:41:38.236 D/ApplicationLoaders( 9330): Returning zygote-cached class loader: /system/framework/android.test.base.jar
02-15 17:41:38.237 I/id.logcollecto( 9330): The ClassLoaderContext is a special shared library.
02-15 17:41:38.248 D/NetworkSecurityConfig( 9330): No Network Security Config specified, using platform default
02-15 17:41:38.248 D/NetworkSecurityConfig( 9330): No Network Security Config specified, using platform default
02-15 17:41:38.252 W/id.logcollector( 9330): type=1400 audit(0.0:2797): avc: denied { read } for name="version" dev="proc" ino=4026532112 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.xtralogic.android.logcollector
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): IO Exception when getting kernel version for Device Info screen
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): java.io.FileNotFoundException: /proc/version: open failed: EACCES (Permission denied)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at libcore.io.IoBridge.open(IoBridge.java:492)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at java.io.FileInputStream.<init>(FileInputStream.java:160)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at java.io.FileInputStream.<init>(FileInputStream.java:115)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at java.io.FileReader.<init>(FileReader.java:58)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at com.xtralogic.android.logcollector.SendLogActivity.getFormattedKernelVersion(SendLogActivity.java:366)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at com.xtralogic.android.logcollector.SendLogActivity.onCreate(SendLogActivity.java:143)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.Activity.performCreate(Activity.java:8000)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.Activity.performCreate(Activity.java:7984)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.os.Handler.dispatchMessage(Handler.java:106)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.os.Looper.loop(Looper.java:223)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.main(ActivityThread.java:7660)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at java.lang.reflect.Method.invoke(Native Method)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at libcore.io.Linux.open(Native Method)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7546)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): at libcore.io.IoBridge.open(IoBridge.java:478)
02-15 17:41:38.260 E/com.xtralogic.android.logcollector( 9330): ... 20 more
02-15 17:41:38.318 I/Gralloc4( 9330): mapper 4.x is not supported
02-15 17:41:38.318 W/Gralloc3( 9330): mapper 3.x is not supported
02-15 17:41:43.256 I/id.logcollecto( 9330): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 12.525ms
02-15 17:41:51.872 W/id.logcollector( 9330): type=1400 audit(0.0:2800): avc: denied { read } for name="version" dev="proc" ino=4026532112 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.xtralogic.android.logcollector
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): IO Exception when getting kernel version for Device Info screen
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): java.io.FileNotFoundException: /proc/version: open failed: EACCES (Permission denied)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at libcore.io.IoBridge.open(IoBridge.java:492)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at java.io.FileInputStream.<init>(FileInputStream.java:160)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at java.io.FileInputStream.<init>(FileInputStream.java:115)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at java.io.FileReader.<init>(FileReader.java:58)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at com.xtralogic.android.logcollector.SendLogActivity.getFormattedKernelVersion(SendLogActivity.java:366)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at com.xtralogic.android.logcollector.SendLogActivity.onCreate(SendLogActivity.java:143)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.Activity.performCreate(Activity.java:8000)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.Activity.performCreate(Activity.java:7984)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.os.Handler.dispatchMessage(Handler.java:106)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.os.Looper.loop(Looper.java:223)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.main(ActivityThread.java:7660)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at java.lang.reflect.Method.invoke(Native Method)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at libcore.io.Linux.open(Native Method)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7546)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): at libcore.io.IoBridge.open(IoBridge.java:478)
02-15 17:41:51.876 E/com.xtralogic.android.logcollector( 9330): ... 20 more
02-15 17:41:52.123 W/InputEventReceiver( 9330): Attempted to finish an input event but the input event receiver has already been disposed.
02-15 17:41:57.072 W/id.logcollector( 9330): type=1400 audit(0.0:2801): avc: denied { read } for name="version" dev="proc" ino=4026532112 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.xtralogic.android.logcollector
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): IO Exception when getting kernel version for Device Info screen
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): java.io.FileNotFoundException: /proc/version: open failed: EACCES (Permission denied)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at libcore.io.IoBridge.open(IoBridge.java:492)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at java.io.FileInputStream.<init>(FileInputStream.java:160)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at java.io.FileInputStream.<init>(FileInputStream.java:115)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at java.io.FileReader.<init>(FileReader.java:58)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at com.xtralogic.android.logcollector.SendLogActivity.getFormattedKernelVersion(SendLogActivity.java:366)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at com.xtralogic.android.logcollector.SendLogActivity.onCreate(SendLogActivity.java:143)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.Activity.performCreate(Activity.java:8000)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.Activity.performCreate(Activity.java:7984)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.os.Handler.dispatchMessage(Handler.java:106)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.os.Looper.loop(Looper.java:223)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread.main(ActivityThread.java:7660)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at java.lang.reflect.Method.invoke(Native Method)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at libcore.io.Linux.open(Native Method)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7546)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): at libcore.io.IoBridge.open(IoBridge.java:478)
02-15 17:41:57.077 E/com.xtralogic.android.logcollector( 9330): ... 20 more
02-15 17:42:06.832 W/com.xtralogic.android.logcollector( 9330): type=1400 audit(0.0:2803): avc: denied { search } for comm=4173796E635461736B202331 name="background" dev="tmpfs" ino=23169 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:blkio:s0 tclass=dir permissive=0 app=com.xtralogic.android.logcollector
02-15 17:42:12.634 W/System  ( 9330): A resource failed to call dispose.
02-15 17:42:12.634 W/System  ( 9330): A resource failed to call release.
02-15 17:42:12.635 W/System  ( 9330): A resource failed to call dispose.
02-15 17:44:01.621 E/id.logcollecto(10034): Not starting debugger since process cannot load the jdwp agent.
02-15 17:44:01.638 D/ApplicationLoaders(10034): Returning zygote-cached class loader: /system/framework/android.test.base.jar
02-15 17:44:01.639 I/id.logcollecto(10034): The ClassLoaderContext is a special shared library.
02-15 17:44:01.649 D/NetworkSecurityConfig(10034): No Network Security Config specified, using platform default
02-15 17:44:01.650 D/NetworkSecurityConfig(10034): No Network Security Config specified, using platform default
02-15 17:44:01.652 W/id.logcollector(10034): type=1400 audit(0.0:2850): avc: denied { read } for name="version" dev="proc" ino=4026532112 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc_version:s0 tclass=file permissive=0 app=com.xtralogic.android.logcollector
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): IO Exception when getting kernel version for Device Info screen
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): java.io.FileNotFoundException: /proc/version: open failed: EACCES (Permission denied)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at libcore.io.IoBridge.open(IoBridge.java:492)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at java.io.FileInputStream.<init>(FileInputStream.java:160)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at java.io.FileInputStream.<init>(FileInputStream.java:115)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at java.io.FileReader.<init>(FileReader.java:58)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at com.xtralogic.android.logcollector.SendLogActivity.getFormattedKernelVersion(SendLogActivity.java:366)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at com.xtralogic.android.logcollector.SendLogActivity.onCreate(SendLogActivity.java:143)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.Activity.performCreate(Activity.java:8000)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.Activity.performCreate(Activity.java:7984)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.os.Handler.dispatchMessage(Handler.java:106)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.os.Looper.loop(Looper.java:223)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.ActivityThread.main(ActivityThread.java:7660)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at java.lang.reflect.Method.invoke(Native Method)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at libcore.io.Linux.open(Native Method)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7546)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): at libcore.io.IoBridge.open(IoBridge.java:478)
02-15 17:44:01.657 E/com.xtralogic.android.logcollector(10034): ... 20 more
02-15 17:44:01.692 I/Gralloc4(10034): mapper 4.x is not supported
02-15 17:44:01.692 W/Gralloc3(10034): mapper 3.x is not supported
02-15 17:44:02.852 W/com.xtralogic.android.logcollector(10034): type=1400 audit(0.0:2851): avc: denied { search } for comm=4173796E635461736B202331 name="background" dev="tmpfs" ino=23169 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:blkio:s0 tclass=dir permissive=0 app=com.xtralogic.android.logcollector

**Comment by imrohitkumar** [comment]
Also, If I'm trying to compile code by myself then this error is comming!
e: C:\Android\RASA-With-Aimybox\app\src\main\java\com\sumit\assistant\util\AppConstants.kt: (8, 48): Expecting an expression
[I have added Aimybox Key]
